version: '2'
services:
    comegoapp-app:
        image: comegoapp
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mariadb://comegoapp-mariadb:3306/comegoapp
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    comegoapp-mariadb:
        extends:
            file: mariadb.yml
            service: comegoapp-mariadb
